services:
  - type: web
    name: gr-portal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        value: https://uhlncqrevycxtxtdydav.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false # Set your private Supabase secret key in the Render Environment tab
      - key: SUPABASE_GOV_USERS_TABLE
        value: gov-users-v2
